### ISSUE TITLE
Unable to use app_settings 7.0.0 with Flutter 3.44 (spm enabled)

### ISSUE THREAD

**Issue by gyrocopterization** [spencerccf/app_settings#271]
# Bug Report: `app_settings 7.0.0` SPM Integration Breaks ObjC Import in Flutter Mixed CocoaPods/SPM Projects

## Summary

`app_settings 7.0.0` fails to build in Flutter projects that use a mixed CocoaPods + Swift Package Manager setup. The module is resolved and compiled successfully via SPM, but `GeneratedPluginRegistrant.m` cannot import it via `@import app_settings`, resulting in a fatal build error.

## Environment

- **Plugin:** `app_settings 7.0.0`
- **Flutter:** 3.44.x
- **Xcode:** 17 (iPhoneOS26.4 SDK)
- **iOS Deployment Target:** 15.0
- **Dependency Manager:** Mixed (CocoaPods + SPM enabled via `flutter config --enable-swift-package-manager`)

## Error

```
ios/Runner/GeneratedPluginRegistrant.m:24:9: fatal error: module 'app_settings' not found
   24 | @import app_settings;
** EXPORT FAILED **
```

### 1. Module name mismatch

Inside `FlutterGeneratedPluginSwiftPackage/Package.swift` (Flutter's auto-generated SPM umbrella package), `app_settings` is declared as a product with a **hyphenated** name:

```swift
.product(name: "app-settings", package: "app_settings"),
```

However, Flutter's `GeneratedPluginRegistrant.m` imports it using an **underscore**:

```objc
@import app_settings;
```

This mismatch causes the ObjC compiler to fail to find the module.

### 2. Module not re-exported to ObjC targets

`app_settings` is listed as a dependency inside `FlutterGeneratedPluginSwiftPackage` but is not re-exported as a standalone product. This means the compiled module is not accessible to ObjC files in the Runner target, even though the SPM modulemap (`app_settings.modulemap`) is correctly generated and passed via `OTHER_CFLAGS`.

### 3. Package builds successfully but is unreachable

The following all succeed:
- SPM resolves `app_settings-7.0.0` ✅
- `AppSettingsPlugin.swift` compiles ✅
- `app_settings.modulemap` is generated ✅
- `app_settings.swiftmodule` is generated ✅
- `app_settings.o` is linked ✅

But when `GeneratedPluginRegistrant.m` (an ObjC file in the Runner target) attempts `@import app_settings`, it fails — meaning the module is built in isolation but never properly linked/exposed to the Runner's ObjC compilation context.

### Evidence from `FlutterGeneratedPluginSwiftPackage/Package.swift`

```swift
dependencies: [
    ...
    .package(name: "app_settings", path: "../.packages/app_settings-7.0.0"),
    ...
],
targets: [
    .target(
        name: "FlutterGeneratedPluginSwiftPackage",
        dependencies: [
            ...
            .product(name: "app-settings", package: "app_settings"),
            ...
        ]
    )
]
```

The plugin is wrapped inside `FlutterGeneratedPluginSwiftPackage` but the ObjC module import path is broken.

## Steps to Reproduce

1. Create or use a Flutter project with CocoaPods as the primary dependency manager
2. Enable SPM: `flutter config --enable-swift-package-manager`
3. Add `app_settings: ^7.0.0` to `pubspec.yaml`
4. Run `flutter pub get && cd ios && pod install`
5. Archive or build for a physical device
6. Observe the fatal error in `GeneratedPluginRegistrant.m`

## Workaround

Downgrading to `app_settings: 5.0.1` (pure ObjC, CocoaPods) and disabling SPM resolves the issue:

```bash
flutter config --no-enable-swift-package-manager
```

```yaml
# pubspec.yaml
app_settings: 5.0.1
```

## Expected Behavior

`app_settings 7.0.0` should be importable via `@import app_settings` in ObjC files when resolved through Flutter's SPM integration, consistent with how other SPM-migrated plugins (e.g. `share_plus`, `device_info_plus`) work.

## Additional Finding: `swift-tools-version: 6.0` Causes Xcode Identity Conflict

Comparing `app_settings 7.0.0`'s `Package.swift` with a working plugin (`share_plus 12.0.2`) reveals a critical difference:

**`app_settings` `Package.swift`:**
```swift
// swift-tools-version: 6.0
let package = Package(
    name: "app_settings",
    products: [
        .library(name: "app-settings", targets: ["app_settings"]),
    ],
    ...
)
```

**`share_plus` `Package.swift` (works correctly):**
```swift
// swift-tools-version: 5.9
let package = Package(
    name: "share_plus",
    products: [
        .library(name: "share-plus", targets: ["share_plus"])
    ],
    ...
)
```

The structure is identical — but `app_settings` declares `swift-tools-version: 6.0` while all working Flutter SPM plugins use `5.9`. Swift 6.0 tools trigger **stricter SPM identity resolution** in Xcode, which causes a conflict when Flutter's `flutter clean` regenerates the ephemeral packages folder. Specifically:

1. `flutter clean` deletes `ios/Flutter/ephemeral` (standard workflow)
2. `flutter pub get` regenerates the package at `ephemeral/Packages/.packages/app_settings-7.0.0`
3. Xcode derives the identity from the directory name `app_settings-7.0.0`
4. But Swift 6.0 tools cause Xcode to strictly validate that the declared package `name: "app_settings"` matches the directory identity `app_settings-7.0.0` — they don't match
5. Result: `unable to override package 'app_settings' because its identity 'app_settings-7.0.0' doesn't match override's identity 'app_settings'`

This is triggered by a **completely standard `flutter clean` workflow** — not by any misconfiguration on the user's side.

## Suggested Fix

1. **Downgrade `swift-tools-version` from `6.0` to `5.9`** in `Package.swift` to match other working Flutter SPM plugins like `share_plus`, `device_info_plus`, etc.
2. Ensure the product name `app-settings` (hyphen) is consistent with what Flutter's `GeneratedPluginRegistrant.m` expects (`app_settings` with underscore), or confirm the module is properly re-exported so ObjC targets can resolve the import.

Please refer to `share_plus` or `device_info_plus` as reference implementations for correct Flutter SPM integration.

**Comment by igordanilovski** [comment]
Same issue here...

**Comment by SajuukGa** [comment]
**Subject**: Same issue here — workaround by patching `swift-tools-version` to 5.9

I'm encountering the exact same issue on my project:
- Flutter 3.44.2
- Xcode 17 / Swift 6.3.3
- app_settings: 7.0.0
- Fully SPM-managed (no CocoaPods)
- `flutter build ios` from CLI succeeds, but building directly from Xcode fails with:
  ```
  ios/Runner/GeneratedPluginRegistrant.m:12:9 Module 'app_settings' not found
  ```

After investigation, I compared `app_settings` with other pure-Swift Flutter SPM plugins that work correctly (`connectivity_plus`, `path_provider_foundation`, `shared_preferences_foundation`). The only structural difference is:

| Plugin | swift-tools-version | Status |
|--------|---------------------|--------|
| `connectivity_plus` | **5.9** | ✅ works |
| `shared_preferences_foundation` | **5.9** | ✅ works |
| `app_settings` | **6.0** | ❌ fails |

All three are pure Swift targets with no ObjC headers — identical SPM structure. The `@import` in `GeneratedPluginRegistrant.m` requires a Clang-compatible module map, which SPM auto-generates for `5.9` targets but not for `6.0` pure Swift targets.

**Workaround** that resolved the issue for me:

In `~/.pub-cache/hosted/pub.dev/app_settings-7.0.0/ios/app_settings/Package.swift`, change line 1 from:
```swift
// swift-tools-version: 6.0
```
to:
```swift
// swift-tools-version: 5.9
```

And pinned the version in `pubspec.yaml`:
```yaml
app_settings: 7.0.0  # was ^7.0.0, pinned to avoid accidental overwrite
```

This confirms the suggestion from the issue description — downgrading `swift-tools-version` to `5.9` (matching other Flutter SPM plugins) resolves the problem without any functional impact. Looking forward to an upstream fix. Thanks!
